Camera: {Focal: 13.971313932573906, High: 650.0}
Center: {Camera_high: 665, Center_X: 317, Center_Y: 272, Front: 325, Horizon: 213,
  Inner: 44, Outer: 278, X: 308, Y: 266}
FPS: 15
HSV:
  Ball: [6, 31, 54, 100, 40, 100]
  Blue: [187, 261, 81, 100, 26, 100]
  Green: [93, 209, 18, 100, 17, 86]
  White: [0, 360, 0, 27, 0, 38]
  Yellow: [44, 70, 8, 56, 20, 100]
  black: {angle: 3, gray: 32}
  white: {angle: 3, gray: 172}
Parameterbutton: 4
SCAN: {Angle_Near_Gap: 4, Angle_range_1: 1, Angle_range_2_3: 5, Dont_Search_Angle_1: 154,
  Dont_Search_Angle_2: 36, Dont_Search_Angle_3: 270, Magn_Far_End: 270, Magn_Far_Start: 190,
  Magn_Middle_Start: 110, Magn_Near_Gap: 2, Magn_Near_Start: 46}
blackItem: {angle: 3, gray: 40}
whiteline: {angle: 4, gray: 100}
